" Plugin configuration {{{1

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin('~/.vim/plugged')

" Modeline
Plug 'itchyny/lightline.vim'

" Syntax highlighting
Plug 'mboughaba/i3config.vim'


" History {{{2
"
" - /home/bln/.vim/plugged/Spacegray.vim/
" - /home/bln/.vim/plugged/ansible-vim/
" - /home/bln/.vim/plugged/ayu-vim/
" - /home/bln/.vim/plugged/coc.nvim/
" - /home/bln/.vim/plugged/ctrlp.vim/
" - /home/bln/.vim/plugged/i3config.vim/
" - /home/bln/.vim/plugged/iceberg.vim/
" - /home/bln/.vim/plugged/lightline.vim/
" - /home/bln/.vim/plugged/nerdtree-git-plugin/
" - /home/bln/.vim/plugged/nerdtree/
" - /home/bln/.vim/plugged/typescript-vim/
" - /home/bln/.vim/plugged/vim-colors-solarized/
" - /home/bln/.vim/plugged/vim-css-color/
" - /home/bln/.vim/plugged/vim-gitgutter/
call plug#end()



" General settings {{{1
nnoremap <SPACE> <Nop>
let mapleader=' '
let maplocalleader=','

filetype plugin on
syntax on

set number
" Show a cursor line but only highlight the line number
set cursorline
highlight CursorLineNR cterm=bold ctermbg=Yellow
highlight CursorLine cterm=NONE ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE
" Set the cursor to a blinking beam | in insert mode and to a block otherwise
autocmd InsertEnter * silent execute "!echo -en \<esc>[5 q"
autocmd InsertLeave * silent execute "!echo -en \<esc>[2 q"

set nowrap

set shiftwidth=2
set tabstop=2
set expandtab

set autoindent
set smartindent

set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

" Folding {{{2
set foldenable
set foldmethod=marker
nnoremap <leader><space> za
