" General settings {{{1
nnoremap <SPACE> <Nop>
let mapleader=' '

set number
set nocompatible
filetype plugin on
syntax on

set expandtab
let shiftwidth=4
let tabstop=4
set autoindent

" Folding {{{2
set foldenable
set foldmethod=marker
nnoremap <leader><space> za

" Plugin configuration {{{1

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'

Plug 'ctrlpvim/ctrlp.vim'

Plug 'pearofducks/ansible-vim'

Plug 'airblade/vim-gitgutter'

Plug 'vimwiki/vimwiki'
"Plug 'tbabej/taskwiki'

call plug#end()

" Plugin config for: lightline {{{2
set laststatus=2

" Plugin config for: vimwiki {{{2
let wiki_iteratec = {}
let wiki_iteratec.path = '~/Documents/iteratec/Notes'
let wiki_iteratec.syntax = 'markdown'
let wiki_iteratec.ext = 'md'

let g:vimwiki_list = [wiki_iteratec]
let g:vimwiki_ext2syntax = {'.md': 'markdown'}
let g:vimwiki_folding = 'expr'

"let g:taskwiki_markup_syntax = 'markdown'
"let g:taskwiki_sort_orders = {'T':'<next>'}
"
"function! TaskwarriorSync()
"  let syncresult = system("task sync")
"  split __Taskwarrior_Sync__
"  normal! ggdG
"  setlocal buftype=nofile
"  call append(0, split(syncresult, '\v\n'))
"endfunction
"nnoremap <leader>tws :call TaskwarriorSync()<CR>

" Plugin config for: CtrlP {{{2
" Setup some default ignores
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
\}

" Use the nearest .git directory as the cwd
" This makes a lot of sense if you are working on a project that is in version
" control. It also supports works with .svn, .hg, .bzr.
let g:ctrlp_working_path_mode = 'r'

" Use a leader instead of the actual named binding
nmap <leader>p :CtrlP<cr>

" Easy bindings for its various modes
nmap <leader>bb :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>
