#! /usr/bin/env sh

/usr/bin/termite --title="Mattermost iteratec" --exec='sh -c "/usr/bin/docker run -it --rm -e TZ=Europe/Berlin -v ~/.config/matterhorn/config-iteratec.ini:/etc/matterhorn/config.ini bennyli/matterhorn"'
