#! /usr/bin/env sh

/usr/bin/alacritty --title "Mattermost OSM" \
                   --command /bin/sh -c "~/.dotfiles/shortcuts/matterhorn-helper.sh --config ~/.config/matterhorn/config-iteratec-osm.ini --name matterhorn-iteratec-osm" 
