#! /usr/bin/env sh

/usr/bin/termite --title="Mattermost Hamburg" --exec='sh -c "/usr/bin/docker run -it --rm -e TZ=Europe/Berlin -v ~/.config/matterhorn/config-iteratec-hh.ini:/etc/matterhorn/config.ini bennyli/matterhorn"'
